# Database Configuration
# PostgreSQL settings for persistent storage of trades, positions, and historical data
database:
  host: localhost # Database host address
  port: 5432 # PostgreSQL default port
  user: trading_bot # Database user (create with appropriate permissions)
  password: your_password # Strong password recommended
  database: trading_bot # Database name
  min_connections: 5 # Minimum connection pool size
  max_connections: 20 # Maximum connection pool size

# Redis Configuration
# Redis settings for real-time state management and caching
redis:
  host: localhost # Redis host address
  port: 6379 # Redis default port
  password: null # Set to null if no password, otherwise your_redis_password
  db: 0 # Redis database number
  max_connections: 10 # Maximum connections in pool

# Jupiter Configuration
# Settings for Jupiter DEX integration
jupiter:
  rpc_endpoint: https://api.mainnet-beta.solana.com # Solana RPC endpoint
  auth_token: your_token # Jupiter API authentication token
  max_price_impact: 0.01 # Maximum allowed price impact (1%)
  min_sol_balance: 0.1 # Minimum SOL balance to maintain

# API Configuration
# REST API and WebSocket settings
api:
  host: 0.0.0.0 # API host (0.0.0.0 for all interfaces)
  port: 8000 # API port
  secret_key: your_secret_key # API authentication secret key

# Trading Configuration
# Global trading parameters and risk management settings
trading:
  max_position_size: 1000 # Maximum position size in USDC
  min_position_size: 10 # Minimum position size in USDC
  max_positions_per_symbol: 3 # Maximum concurrent positions per symbol
  default_stop_loss_percent: 0.05 # Default stop loss (5%)
  risk_factor: 0.02 # Risk factor for position sizing (2%)
